=== chrismigut/SOAP_Services/PatientXML/Patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Patient"
	xmlns:tns="http://www.example.org/Patient" elementFormDefault="qualified">
	<!-- qualified or unqualified is if the xml file using the schema should 
		use prefix -->
	<!-- Root Element of type Patient -->
	<element name="patient" type="tns:Patient" />

	<!-- Custom data type -->
	<complexType name="Patient">
		<sequence>
			<!-- More common for Id fields to be attributes than elements
			 <element name="id" type="tns:ID" /> -->
			<element name="name" type="tns:String15Chars" />
			<element name="age" type="int" minOccurs="0" /> <!-- optional field -->
			<element name="DOB" type="date" />
			<element name="email" type="string" maxOccurs="unbounded" />
			<element name="gender" type="tns:Gender" />
			<element name="phone" type="string" maxOccurs="2" />
			<element name="paymentType" type="tns:PaymentType" />
		</sequence>
		
		<attribute name="id" type="tns:ID"/>
	</complexType>

	<complexType name="PaymentType">
		<choice>
			<element name="cash" type="int" />
			<element name="insurance" type="tns:Insurance" />
		</choice>
	</complexType>

	<complexType name="Insurance">
		<!-- All elements should show, order doesn't matter -->
		<all>
			<element name="provider" type="string" />
			<element name="limit" type="int" />
		</all>
	</complexType>


	<!-- Adding restrictions on the values allowed in complex type fields -->
	<simpleType name="ID">
		<restriction base="int">
			<pattern value="[0-9]*"></pattern>
		</restriction>
	</simpleType>

	<simpleType name="String15Chars">
		<restriction base="string">
			<maxLength value="15" />
		</restriction>
	</simpleType>

	<simpleType name="Gender">
		<restriction base="string">
			<enumeration value="M"></enumeration>
			<enumeration value="F"></enumeration>
		</restriction>
	</simpleType>

</schema>

=== chrismigut/SOAP_Services/PatientXML/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://www.example.org/Patient" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Patient Patient.xsd ">
  <tns:name>tns:name</tns:name>
  <tns:DOB>2001-01-01</tns:DOB>
  <tns:email>tns:email</tns:email>
  <tns:gender>M</tns:gender>
  <tns:phone>tns:phone</tns:phone>
  <tns:paymentType>
    <tns:cash>0</tns:cash>
  </tns:paymentType>
</tns:patient>
